import {
  StorefrontIcon,
  MagnifyingGlassIcon,
  ReceiptIcon,
  PackageIcon,
  GearSixIcon,
  HouseIcon,
  UserIcon,
  SignOutIcon,
  CaretDownIcon,
  CaretRightIcon,
  BellIcon,
  ListIcon,
  XIcon,
  CommandIcon,
  QuestionIcon,
  PlusIcon,
  PencilSimpleIcon,
  TrashIcon,
  ArrowSquareOutIcon,
  CopyIcon,
  ArchiveIcon,
  CheckIcon,
  GlobeIcon,
  DotsSixVerticalIcon,
  ImageIcon,
  MapPinIcon,
  ClockIcon,
  ChatCircleTextIcon,
  QuestionMarkIcon,
  MagnifyingGlassPlusIcon,
  SidebarSimpleIcon,
  InstagramLogoIcon,
  FacebookLogoIcon,
  XLogoIcon,
  TiktokLogoIcon,
  YoutubeLogoIcon,
  PhoneIcon,
  WhatsappLogoIcon,
  EnvelopeSimpleIcon,
  InfoIcon,
  LightningIcon,
  IdentificationCardIcon,
  ScalesIcon,
  UsersThreeIcon,
} from '@phosphor-icons/react/dist/ssr';

const ICONS = {
  Storefront: StorefrontIcon,
  MagnifyingGlass: MagnifyingGlassIcon,
  Receipt: ReceiptIcon,
  Package: PackageIcon,
  GearSix: GearSixIcon,
  House: HouseIcon,
  User: UserIcon,
  SignOut: SignOutIcon,
  CaretDown: CaretDownIcon,
  CaretRight: CaretRightIcon,
  Bell: BellIcon,
  List: ListIcon,
  X: XIcon,
  Command: CommandIcon,
  Question: QuestionIcon,
  Plus: PlusIcon,
  PencilSimple: PencilSimpleIcon,
  Trash: TrashIcon,
  ArrowSquareOut: ArrowSquareOutIcon,
  Copy: CopyIcon,
  Archive: ArchiveIcon,
  Check: CheckIcon,
  Globe: GlobeIcon,
  DotsSixVertical: DotsSixVerticalIcon,
  Image: ImageIcon,
  MapPin: MapPinIcon,
  Clock: ClockIcon,
  ChatCircleText: ChatCircleTextIcon,
  QuestionMark: QuestionMarkIcon,
  MagnifyingGlassPlus: MagnifyingGlassPlusIcon,
  SidebarSimple: SidebarSimpleIcon,
  InstagramLogo: InstagramLogoIcon,
  FacebookLogo: FacebookLogoIcon,
  XLogo: XLogoIcon,
  TiktokLogo: TiktokLogoIcon,
  YoutubeLogo: YoutubeLogoIcon,
  Phone: PhoneIcon,
  WhatsappLogo: WhatsappLogoIcon,
  EnvelopeSimple: EnvelopeSimpleIcon,
  Info: InfoIcon,
  Lightning: LightningIcon,
  IdentificationCard: IdentificationCardIcon,
  Scales: ScalesIcon,
  UsersThree: UsersThreeIcon,
} as const;

export type IconName = keyof typeof ICONS;

export function NavIcon({
  name,
  size = 18,
  weight = 'regular',
  className,
}: {
  name: IconName;
  size?: number;
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
  className?: string;
}) {
  const Cmp = ICONS[name];
  return <Cmp size={size} weight={weight} className={className} aria-hidden />;
}
